### ISSUE TITLE
Errors don't return CORS headers

### ISSUE THREAD

**Issue by SiggyF** [openearth/hydro-engine-service#15]
### Description

If a method returns an error message in json format. It should also return the appropriate cors headers. Otherwise the error message cannot be loaded in an application using the service under a different url.

### What I Did

Given the following request body:
```
{
	"liwo_ids": [1903,1948],
	"band": "waterdepth",
	"reducer": "max"
}
```
Post to the url `/get_liwo_scenarios`.

I get back the following result:
```
{
    "message": "No images available for breach locations: [1903, 1948]"
}
```
But without the appropriate header `Access-Control-Allow-Origin: *`

**Comment by evetion** [comment]
Closed by #16
